# runner server
# takes in miner code, takes in info representing SWE tasks (generated by the validator), 
# caches tasks , or slowly get sent 
# or have tasks generated by the runner so that it doesnt have to rebuild docker containers and other things, 1000 containers is a lot to build

